package com.braunster.chatsdk.dao;

import java.util.List;
import java.util.ArrayList;
import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteStatement;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.Property;
import de.greenrobot.dao.internal.SqlUtils;
import de.greenrobot.dao.internal.DaoConfig;
import de.greenrobot.dao.query.Query;
import de.greenrobot.dao.query.QueryBuilder;

import com.braunster.chatsdk.dao.BMessageReceipt;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table BMESSAGE_RECEIPT.
*/
public class BMessageReceiptDao extends AbstractDao<BMessageReceipt, Long> {

    public static final String TABLENAME = "BMESSAGE_RECEIPT";

    /**
     * Properties of entity BMessageReceipt.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property ReadStatus = new Property(1, Integer.class, "readStatus", false, "READ_STATUS");
        public final static Property ReaderId = new Property(2, Long.class, "readerId", false, "READER_ID");
        public final static Property BMessageId = new Property(3, Long.class, "BMessageId", false, "BMESSAGE_ID");
    };

    private DaoSession daoSession;

    private Query<BMessageReceipt> bMessage_BMessageReceiptListQuery;

    public BMessageReceiptDao(DaoConfig config) {
        super(config);
    }
    
    public BMessageReceiptDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
        this.daoSession = daoSession;
    }

    /** Creates the underlying database table. */
    public static void createTable(SQLiteDatabase db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "'BMESSAGE_RECEIPT' (" + //
                "'_id' INTEGER PRIMARY KEY ," + // 0: id
                "'READ_STATUS' INTEGER," + // 1: readStatus
                "'READER_ID' INTEGER," + // 2: readerId
                "'BMESSAGE_ID' INTEGER);"); // 3: BMessageId
    }

    /** Drops the underlying database table. */
    public static void dropTable(SQLiteDatabase db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "'BMESSAGE_RECEIPT'";
        db.execSQL(sql);
    }

    /** @inheritdoc */
    @Override
    protected void bindValues(SQLiteStatement stmt, BMessageReceipt entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        Integer readStatus = entity.getReadStatus();
        if (readStatus != null) {
            stmt.bindLong(2, readStatus);
        }
 
        Long readerId = entity.getReaderId();
        if (readerId != null) {
            stmt.bindLong(3, readerId);
        }
 
        Long BMessageId = entity.getBMessageId();
        if (BMessageId != null) {
            stmt.bindLong(4, BMessageId);
        }
    }

    @Override
    protected void attachEntity(BMessageReceipt entity) {
        super.attachEntity(entity);
        entity.__setDaoSession(daoSession);
    }

    /** @inheritdoc */
    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    /** @inheritdoc */
    @Override
    public BMessageReceipt readEntity(Cursor cursor, int offset) {
        BMessageReceipt entity = new BMessageReceipt( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getInt(offset + 1), // readStatus
            cursor.isNull(offset + 2) ? null : cursor.getLong(offset + 2), // readerId
            cursor.isNull(offset + 3) ? null : cursor.getLong(offset + 3) // BMessageId
        );
        return entity;
    }
     
    /** @inheritdoc */
    @Override
    public void readEntity(Cursor cursor, BMessageReceipt entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setReadStatus(cursor.isNull(offset + 1) ? null : cursor.getInt(offset + 1));
        entity.setReaderId(cursor.isNull(offset + 2) ? null : cursor.getLong(offset + 2));
        entity.setBMessageId(cursor.isNull(offset + 3) ? null : cursor.getLong(offset + 3));
     }
    
    /** @inheritdoc */
    @Override
    protected Long updateKeyAfterInsert(BMessageReceipt entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    /** @inheritdoc */
    @Override
    public Long getKey(BMessageReceipt entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    /** @inheritdoc */
    @Override    
    protected boolean isEntityUpdateable() {
        return true;
    }
    
    /** Internal query to resolve the "bMessageReceiptList" to-many relationship of BMessage. */
    public List<BMessageReceipt> _queryBMessage_BMessageReceiptList(Long BMessageId) {
        synchronized (this) {
            if (bMessage_BMessageReceiptListQuery == null) {
                QueryBuilder<BMessageReceipt> queryBuilder = queryBuilder();
                queryBuilder.where(Properties.BMessageId.eq(null));
                bMessage_BMessageReceiptListQuery = queryBuilder.build();
            }
        }
        Query<BMessageReceipt> query = bMessage_BMessageReceiptListQuery.forCurrentThread();
        query.setParameter(0, BMessageId);
        return query.list();
    }

    private String selectDeep;

    protected String getSelectDeep() {
        if (selectDeep == null) {
            StringBuilder builder = new StringBuilder("SELECT ");
            SqlUtils.appendColumns(builder, "T", getAllColumns());
            builder.append(',');
            SqlUtils.appendColumns(builder, "T0", daoSession.getBUserDao().getAllColumns());
            builder.append(" FROM BMESSAGE_RECEIPT T");
            builder.append(" LEFT JOIN BUSER T0 ON T.'READER_ID'=T0.'_id'");
            builder.append(' ');
            selectDeep = builder.toString();
        }
        return selectDeep;
    }
    
    protected BMessageReceipt loadCurrentDeep(Cursor cursor, boolean lock) {
        BMessageReceipt entity = loadCurrent(cursor, 0, lock);
        int offset = getAllColumns().length;

        BUser reader = loadCurrentOther(daoSession.getBUserDao(), cursor, offset);
        entity.setReader(reader);

        return entity;    
    }

    public BMessageReceipt loadDeep(Long key) {
        assertSinglePk();
        if (key == null) {
            return null;
        }

        StringBuilder builder = new StringBuilder(getSelectDeep());
        builder.append("WHERE ");
        SqlUtils.appendColumnsEqValue(builder, "T", getPkColumns());
        String sql = builder.toString();
        
        String[] keyArray = new String[] { key.toString() };
        Cursor cursor = db.rawQuery(sql, keyArray);
        
        try {
            boolean available = cursor.moveToFirst();
            if (!available) {
                return null;
            } else if (!cursor.isLast()) {
                throw new IllegalStateException("Expected unique result, but count was " + cursor.getCount());
            }
            return loadCurrentDeep(cursor, true);
        } finally {
            cursor.close();
        }
    }
    
    /** Reads all available rows from the given cursor and returns a list of new ImageTO objects. */
    public List<BMessageReceipt> loadAllDeepFromCursor(Cursor cursor) {
        int count = cursor.getCount();
        List<BMessageReceipt> list = new ArrayList<BMessageReceipt>(count);
        
        if (cursor.moveToFirst()) {
            if (identityScope != null) {
                identityScope.lock();
                identityScope.reserveRoom(count);
            }
            try {
                do {
                    list.add(loadCurrentDeep(cursor, false));
                } while (cursor.moveToNext());
            } finally {
                if (identityScope != null) {
                    identityScope.unlock();
                }
            }
        }
        return list;
    }
    
    protected List<BMessageReceipt> loadDeepAllAndCloseCursor(Cursor cursor) {
        try {
            return loadAllDeepFromCursor(cursor);
        } finally {
            cursor.close();
        }
    }
    

    /** A raw-style query where you can pass any WHERE clause and arguments. */
    public List<BMessageReceipt> queryDeep(String where, String... selectionArg) {
        Cursor cursor = db.rawQuery(getSelectDeep() + where, selectionArg);
        return loadDeepAllAndCloseCursor(cursor);
    }
 
}
